fix: if condition logic

diff --git a/.github/workflows/release-cut.yaml b/.github/workflows/release-cut.yaml
--- a/.github/workflows/release-cut.yaml
+++ b/.github/workflows/release-cut.yaml
@@ -27,10 +27,10 @@ jobs:
     - name: "Cut Release Branch"
       run: |
         git branch -a | grep $RELEASE_BRANCH;
-        if [ "$?" -eq 0 ]; then
-          echo "::error::Release Branch Already Exists";
-          exit 1;
-        fi
+        if [ $? -eq 0 ]; then
+  echo "::error::Release Branch Already Exists";
+  exit 1;
+fi
         git config --global user.name 'Release Cut'
         git config --global user.email 'release@cut.com'
         git checkout -b $RELEASE_BRANCH;
