fix: stop if release branch exists already (no-new-features)

diff --git a/.github/workflows/release-cut.yaml b/.github/workflows/release-cut.yaml
--- a/.github/workflows/release-cut.yaml
+++ b/.github/workflows/release-cut.yaml
@@ -23,8 +23,14 @@ jobs:
         echo "##[set-output name=minor;]$(./git-mkver-linux next --format '{Minor}')";
         echo "##[set-output name=patch;]$(./git-mkver-linux next --format '{Patch}')";
     
+    # TODO: if $RELEASE_BRANCH exists, fail action
     - name: "Cut Release Branch"
       run: |
+        git branch -a | grep $RELEASE_BRANCH
+        if [ $? -ne 0 ]; then
+          echo "::error ::Release Branch Already Exists"
+          exit -1;
+        fi
         git config --global user.name 'Release Cut'
         git config --global user.email 'release@cut.com'
         git checkout -b $RELEASE_BRANCH;
@@ -42,7 +48,7 @@ jobs:
         source_branch: release-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
         destination_branch: "main" 
         pr_title: release-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
-        pr_body: "TODO: use short commit log" # TODO: generate changelog
+        pr_body: "TODO: use short commit log" # TODO: generate changelog from short git log
         # pr_label: release
 
     # Note: This increments minor version only, for now major releases will be done manually
